[workspace]
resolver = "2"
members = [
    "neco-algnum",
    "neco-bigint",
    "neco-complex",
    "neco-expr",
    "neco-linear-types",
    "neco-linear-dense",
    "neco-linear-exact",
    "neco-generalized-eigen",
    "neco-eigensolve",
    "neco-eigensolve-faer",
    "neco-sparse",
    "neco-formsum",
    "neco-monomial",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.82"
license = "MIT"
repository = "https://github.com/barineco/neco-algebra"
